### ISSUE TITLE
another small change request

### ISSUE THREAD

**Issue by Perecli** [i8beef/Ecobee#7]
Looking at the Client class I noticed this:
```
private TimeSpan _timeout = TimeSpan.FromSeconds(30);
```
But this is not used anywhere so my assumption is that you intended to implement a timeout at some point and never did. 

Well I was going to externally implement my own time out with this function:

```
    Public Async Function WithTimeout(Of TResult)(
            sctTimeout As TimeSpan,
            objAsyncFunc As Func(Of CancellationToken, Task(Of TResult)),
            Optional strErrorMsg As String = Nothing
        ) As Task(Of TResult)

        Dim objCts = New CancellationTokenSource(sctTimeout.TotalMilliseconds)
        Try
            Return Await objAsyncFunc.Invoke(objCts.Token)
        Catch ex As TaskCanceledException
            If strErrorMsg = Nothing Then
                Throw ex
            Else
                Throw New ApplicationException(strErrorMsg)
            End If
        End Try

    End Function
```

But then I would have to call each API function like this:

```
Dim strResult = Await WithTimeout(TimeSpan.FromMilliseconds(30000), Async Function(ct) Await TestAsync(2000, ct), "Ecobee servers did not respond in time.")
```

This works but it would be so much nicer if it was included in the Client class of the API. You're welcome to use this global function which adds the timeout feature to any async function that takes a cancelation token. All yours do.

**Comment by Perecli** [comment]
If you implement the above, also make the Client.Timeout property public.

**Comment by i8beef** [comment]
Closing in favor of your other ticket to discuss.
